const fs = require('fs');
const L = [];
L.push('"use client";');
L.push('');
L.push('import { useEffect, useState, Suspense } from "react";');
L.push('import { useParams, useSearchParams } from "next/navigation";');
L.push('import TeaserReport from "@/components/TeaserReport";');
L.push('import FullReportView from "@/components/FullReportView";');
L.push('import { Loader2, AlertCircle, ArrowLeft } from "lucide-react";');
L.push('import Link from "next/link";');
L.push('');
L.push('function AuditDetailContent() {');
L.push('  const params = useParams();');
L.push('  const searchParams = useSearchParams();');
L.push('  const id = params?.id as string;');
L.push('  const isJustUnlocked = searchParams.get("unlocked") === "true";');
L.push('');
L.push('  const [loading, setLoading] = useState(true);');
L.push('  const [data, setData] = useState<any>(null);');
L.push('  const [error, setError] = useState<string | null>(null);');
L.push('');
L.push('  useEffect(() => {');
L.push('    if (!id) return;');
L.push('    fetch(`/api/audit/${id}`)');
L.push('      .then((res) => { if (!res.ok) throw new Error("Audit report not found"); return res.json(); })');
L.push('      .then((resData) => { setData(resData); setLoading(false); })');
L.push('      .catch((err) => { setError(err.message); setLoading(false); });');
L.push('  }, [id, isJustUnlocked]);');
L.push('');
L.push('  if (loading) { return (<div className="min-h-[70vh] flex flex-col items-center justify-center space-y-4"><Loader2 className="w-8 h-8 animate-spin text-indigo-400"/><p className="text-xs font-mono text-slate-400">Loading Business Intelligence Report...</p></div>); }');
L.push('  if (error || !data?.audit) { return (<div className="min-h-[60vh] flex flex-col items-center justify-center px-4"><div className="max-w-md w-full p-6 rounded-2xl border border-rose-500/20 bg-rose-500/10 text-center space-y-4"><AlertCircle className="w-8 h-8 text-rose-400 mx-auto"/><h2 className="text-lg font-semibold text-white">Report Unavailable</h2><p className="text-xs text-rose-300">{error || "Unable to load audit report."}</p><Link href="/" className="inline-flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 pt-2 font-medium"><ArrowLeft className="w-3.5 h-3.5"/><span>Return to Audit Scanner</span></Link></div></div>); }');
L.push('');
L.push('  const { audit, reportData, tierPrices } = data;');
L.push('  const currentTier = audit.tier || "SNAPSHOT";');
L.push('');
L.push('  return (');
L.push('    <div className="py-8 sm:py-12 px-4 sm:px-6 lg:px-8">');
L.push('      {audit.isPaid || isJustUnlocked ? (');
L.push('        <FullReportView');
L.push('          auditId={audit.id}');
L.push('          businessName={audit.businessName}');
L.push('          url={audit.url}');
L.push('          industry={audit.industry}');
L.push('          location={audit.location}');
L.push('          overallScore={audit.overallScore}');
L.push('          reportData={reportData}');
L.push('          tier={currentTier}');
L.push('          tierPrices={tierPrices}');
L.push('        />');
L.push('      ) : (');
L.push('        <TeaserReport');
L.push('          auditId={audit.id}');
L.push('          businessName={audit.businessName}');
L.push('          url={audit.url}');
L.push('          industry={audit.industry}');
L.push('          location={audit.location}');
L.push('          overallScore={audit.overallScore}');
L.push('          reportData={reportData}');
L.push('          tierPrices={tierPrices}');
L.push('        />');
L.push('      )}');
L.push('    </div>');
L.push('  );');
L.push('}');
L.push('');
L.push('export default function AuditDetailPage() {');
L.push('  return (');
L.push('    <Suspense fallback={<div className="min-h-[70vh] flex flex-col items-center justify-center space-y-4"><Loader2 className="w-8 h-8 animate-spin text-indigo-400"/><p className="text-xs font-mono text-slate-400">Loading Business Intelligence Report...</p></div>}>');
L.push('      <AuditDetailContent />');
L.push('    </Suspense>');
L.push('  );');
L.push('}');
L.push('');

const content = L.join('\n');
fs.writeFileSync('src/app/audit/[id]/page.tsx', content, 'utf8');
console.log('audit/[id]/page.tsx written:', content.length, 'bytes');
